package net.exkazuu.battle2048.game;

public enum DefeatReason {
  TIME_LIMIT_EXCEEDED_AT_INIT,
  PRESENTATION_ERROR_AT_INIT,
  INVALID_POSITION_AT_INIT,
  TIME_LIMIT_EXCEEDED_AT_MAIN_OR_ATTACK,
  PRESENTATION_ERROR_AT_MAIN_OR_ATTACK,
  CANNOT_MOVE_AT_MAIN,
  INVALID_M_AND_V_AT_ATTACK,
  INVALID_NUMBER_OF_R_AND_C_AT_ATTACK,
  INVALID_POSITION_AT_ATTACK,
  ALREADY_OCCUPIED_AT_ATTACK,
  LESS_SCORE_AT_END,
  FIRST_BUT_SAME_SCORE_AT_END,
}
